/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSuggestionsRouteImport } from './routes/_app.suggestions'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppRewriterRouteImport } from './routes/_app.rewriter'
import { Route as AppDuplicatesRouteImport } from './routes/_app.duplicates'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBoardRouteImport } from './routes/_app.board'
import { Route as AppBacklogRouteImport } from './routes/_app.backlog'
import { Route as ApiPublicJiraPollRouteImport } from './routes/api/public/jira-poll'
import { Route as AppNotificationsKeyRouteImport } from './routes/_app.notifications.$key'
import { Route as ApiPublicHooksPreventiveSchedulerRouteImport } from './routes/api/public/hooks/preventive-scheduler'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSuggestionsRoute = AppSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppRewriterRoute = AppRewriterRouteImport.update({
  id: '/rewriter',
  path: '/rewriter',
  getParentRoute: () => AppRoute,
} as any)
const AppDuplicatesRoute = AppDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicJiraPollRoute = ApiPublicJiraPollRouteImport.update({
  id: '/api/public/jira-poll',
  path: '/api/public/jira-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsKeyRoute = AppNotificationsKeyRouteImport.update({
  id: '/notifications/$key',
  path: '/notifications/$key',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksPreventiveSchedulerRoute =
  ApiPublicHooksPreventiveSchedulerRouteImport.update({
    id: '/api/public/hooks/preventive-scheduler',
    path: '/api/public/hooks/preventive-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backlog': typeof AppBacklogRoute
  '/board': typeof AppBoardRoute
  '/chat': typeof AppChatRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/rewriter': typeof AppRewriterRoute
  '/risk': typeof AppRiskRoute
  '/suggestions': typeof AppSuggestionsRoute
  '/team': typeof AppTeamRoute
  '/notifications/$key': typeof AppNotificationsKeyRoute
  '/api/public/jira-poll': typeof ApiPublicJiraPollRoute
  '/api/public/hooks/preventive-scheduler': typeof ApiPublicHooksPreventiveSchedulerRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backlog': typeof AppBacklogRoute
  '/board': typeof AppBoardRoute
  '/chat': typeof AppChatRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/rewriter': typeof AppRewriterRoute
  '/risk': typeof AppRiskRoute
  '/suggestions': typeof AppSuggestionsRoute
  '/team': typeof AppTeamRoute
  '/': typeof AppIndexRoute
  '/notifications/$key': typeof AppNotificationsKeyRoute
  '/api/public/jira-poll': typeof ApiPublicJiraPollRoute
  '/api/public/hooks/preventive-scheduler': typeof ApiPublicHooksPreventiveSchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/backlog': typeof AppBacklogRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/duplicates': typeof AppDuplicatesRoute
  '/_app/rewriter': typeof AppRewriterRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/suggestions': typeof AppSuggestionsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/': typeof AppIndexRoute
  '/_app/notifications/$key': typeof AppNotificationsKeyRoute
  '/api/public/jira-poll': typeof ApiPublicJiraPollRoute
  '/api/public/hooks/preventive-scheduler': typeof ApiPublicHooksPreventiveSchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/backlog'
    | '/board'
    | '/chat'
    | '/duplicates'
    | '/rewriter'
    | '/risk'
    | '/suggestions'
    | '/team'
    | '/notifications/$key'
    | '/api/public/jira-poll'
    | '/api/public/hooks/preventive-scheduler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/backlog'
    | '/board'
    | '/chat'
    | '/duplicates'
    | '/rewriter'
    | '/risk'
    | '/suggestions'
    | '/team'
    | '/'
    | '/notifications/$key'
    | '/api/public/jira-poll'
    | '/api/public/hooks/preventive-scheduler'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/backlog'
    | '/_app/board'
    | '/_app/chat'
    | '/_app/duplicates'
    | '/_app/rewriter'
    | '/_app/risk'
    | '/_app/suggestions'
    | '/_app/team'
    | '/_app/'
    | '/_app/notifications/$key'
    | '/api/public/jira-poll'
    | '/api/public/hooks/preventive-scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicJiraPollRoute: typeof ApiPublicJiraPollRoute
  ApiPublicHooksPreventiveSchedulerRoute: typeof ApiPublicHooksPreventiveSchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suggestions': {
      id: '/_app/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof AppSuggestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewriter': {
      id: '/_app/rewriter'
      path: '/rewriter'
      fullPath: '/rewriter'
      preLoaderRoute: typeof AppRewriterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duplicates': {
      id: '/_app/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof AppDuplicatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backlog': {
      id: '/_app/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/jira-poll': {
      id: '/api/public/jira-poll'
      path: '/api/public/jira-poll'
      fullPath: '/api/public/jira-poll'
      preLoaderRoute: typeof ApiPublicJiraPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications/$key': {
      id: '/_app/notifications/$key'
      path: '/notifications/$key'
      fullPath: '/notifications/$key'
      preLoaderRoute: typeof AppNotificationsKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/preventive-scheduler': {
      id: '/api/public/hooks/preventive-scheduler'
      path: '/api/public/hooks/preventive-scheduler'
      fullPath: '/api/public/hooks/preventive-scheduler'
      preLoaderRoute: typeof ApiPublicHooksPreventiveSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBacklogRoute: typeof AppBacklogRoute
  AppBoardRoute: typeof AppBoardRoute
  AppChatRoute: typeof AppChatRoute
  AppDuplicatesRoute: typeof AppDuplicatesRoute
  AppRewriterRoute: typeof AppRewriterRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSuggestionsRoute: typeof AppSuggestionsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNotificationsKeyRoute: typeof AppNotificationsKeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBacklogRoute: AppBacklogRoute,
  AppBoardRoute: AppBoardRoute,
  AppChatRoute: AppChatRoute,
  AppDuplicatesRoute: AppDuplicatesRoute,
  AppRewriterRoute: AppRewriterRoute,
  AppRiskRoute: AppRiskRoute,
  AppSuggestionsRoute: AppSuggestionsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppNotificationsKeyRoute: AppNotificationsKeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicJiraPollRoute: ApiPublicJiraPollRoute,
  ApiPublicHooksPreventiveSchedulerRoute:
    ApiPublicHooksPreventiveSchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
